name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wubin2/it-tools@master
      - name: Sync with upstream
        uses: CorentinTh/it-tools@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
